# Generated by Django 6.0.3 on 2026-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_appointment_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2026-03-20'),
        ),
    ]
